name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up Node.js
        uses: actions/setup-node@v2
        
        with: 
          node-version: '18'

      - name: Install dependencies
        run: cd front-end && npm i

      - name: build generation
        run: cd front-end && npm run build

      - name: zip build
        run: zip -r project.zip front-end/build

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6  # Adjust to your desired Terraform version

      - name: Terraform Init
        run: terraform init
        working-directory: ./tf_infrastructure

        # working-directory: ./tf_infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./tf_infrastructure

      - name: Terraform Apply
        run: terraform apply -auto-approve



          